### ISSUE TITLE
不支持metro应用么

### ISSUE THREAD

**Issue by CodeFalling** [TransposonY/GestureSign#1]
试了下界面很清新，但是似乎不支持metro应用?

**Comment by TransposonY** [comment]
你好，应当是支持的

**Comment by CodeFalling** [comment]
我是Windows8.1Pro 32位，在x86平板上，然而在metro应用下画手势（简单的双指向右）时，连线都没有出现。在桌面应用下一切正常。

**Comment by TransposonY** [comment]
在App里没有轨迹是正常的，要在App里显示顶层窗口，微软要求软件经过数字签名，且安装在program file里，这个我在下一版本0.10版的安装版实现了
