### ISSUE TITLE
Some things...

### ISSUE THREAD

**Issue by schaden-freude** [TransposonY/GestureSign#10]
Hi!

In the 2.1 release notes, what does the "Multiple gestures support" mean? In addition, when I create a new gesture, the resulting output has a new "Overlay Gesture" button, just below the detected gesture. What does that mean and how do I use that?

The two finger gestures of swiping from left/right do not take into account the positions of the fingers. I mean, the gesture is the same irrespective of whether my fingers are side by side by side or one below the other. Is it possible to add that distinction? [Image] (http://i.imgur.com/7qbK1Lk.gif?1)

Moreover, an addition of hold one finger and tap gesture would be great. You tap and hold your middle finger on the screen, and then, with a short delay, you tap on the left/right/up/down with another finger while still keeping the middle finger at the same place. Currently, this is recognized as a double tap. A distinction of where you tap i.e. whether left/right/up/down would be nice.

**Comment by TransposonY** [comment]
"Multiple gestures support" means you can combine several gestures into one gesture such as combine two two-finger-tap gestures into a two-finger-double-tap gesture.That button is utilized to merge gestures.
Your needs can be achieved by adding a new command that you can write scripts to distinguish gestures by each finger's position.
