### ISSUE TITLE
Can't add double tap gesture

### ISSUE THREAD

**Issue by paulens12** [TransposonY/GestureSign#11]
There is a built-in 3-finger double tap gesture. I want the same but with 2 and 4 fingers. However, it's impossible to do this because when the software is in "learning mode", it stops listening and a window appears as soon as I release my fingers.
So, it's impossible to add a double tap gesture.

**Comment by TransposonY** [comment]
You can add double tap gestures by following steps:
After your 2-finger(or 4-finger) tap, click "Overlay Gesture" button, then repeat your previous gesture(2-finger or 4-finger tap).

**Comment by catharinavas** [comment]
Hey, where is the Overlay Gesture button? I was not able to find it...
