### ISSUE TITLE
New Action type

### ISSUE THREAD

**Issue by JoseConseco** [TransposonY/GestureSign#12]
Some apps wait for combination of keyboard key press plus mouse click eg.
- ctrl + Left MB  - works as color picker.
Gesture sign can send key down action, but then it stays down.  I wish there would be new action type:
- press and hold key, until users preses some mouse button. After users perform action with mouse, release the key (send key up action).
See EasyStroke has this functionality [here](https://github.com/thjaeger/easystroke/wiki/Documentation#ignore)

**Comment by TransposonY** [comment]
GestureSign can fire series of actions by one stroke. 
![act](https://cloud.githubusercontent.com/assets/9271096/24596997/9b6abd0c-1875-11e7-9b6b-75108d916b52.png)

![gif](https://cloud.githubusercontent.com/assets/9271096/24597011/ac1c4eb8-1875-11e7-9c39-d36254956f4b.gif)

**Comment by JoseConseco** [comment]
thanks. seems to work ok. Is there donation button for this app?

**Comment by Thalonius** [comment]
Hi, I'm using GestureSign for a while and was interested to see, that Mouse-Gestures were added, but I don't know how to configure them.
If I select "Right Button" it says "None+'Right Button'", but I can't save it.

I tried drawing a gesture, then switch to tab "Mouse" and set a value. This let's me press save, but only saves the gesture.

How is this supposed to work?
Thank you!
Thalon
