### ISSUE TITLE
This app needs continuous gestures

### ISSUE THREAD

**Issue by x-iso** [TransposonY/GestureSign#13]
Hi! First of all, big thanks for making this app! It seems very strange to me that even Windows 10 still doesn't have anything alike built in, despite Microsoft's quite successful efforts in pushing touchscreen PC to the masses. 

I've been using TouchMe gesture studio for a while, but often have to turn it off entirely, since it only does gestures globally and can interfere with apps that do require multi-touch input. One great thing that it does though and which I didn't found here is continuous gestures. It means that when you do a swiping, pinching or rotating gestures, the assigned value is changing according to movement, for instance you can change brightness or volume by rotating an 'invisible dial' with 5 fingers, the great thing about it is that you can go back and forth as you do the gesture and settle on desirable value all in one gesture. But as I've said it can mess up with apps that do engage with multiple fingers and there was no updates for ages. That's why I've found your app as alternative.

If you could implement continuous gestures (dragging/pinching/rotating), it could enable tons of potential for touchscreen interaction, when combined with existing features of GestureSign and also would be great to combine them with other gestures, like holding with one, two or more fingers on the side while performing continuous gesture on the other side resulting in different actions.

One thing in particular I would like to use is following type of gesture: place three fingers close to each other on the screen, drag them around to dismiss other possible gestures like swipes with three fingers and when this condition met - show mouse cursor either to the left or to the right of top-most point of gesture (depending on curvature of points placement), and move it along with fingers. When additional tap occurs (with index finger) - LMB is used, or RMB for long tap. Mouse movement can be set up with acceleration to be able to reach all the corners of the screen

Or maybe I'm missing something and gestures like that already possible?

**Comment by Thalonius** [comment]
I second the idea of continuous gestures. I really like the idea of changing the volume with a circular movement of my fingers.

@x-iso I don't think something like this is directly possible with GestureSign, but it can be done in a similar way with "TouchMousePointer". Just google for it.
I've used TMP on my tablet for a long time now and it's pretty perfect to do a fine navigation when there is no touchpad or mouse available.

**Comment by x-iso** [comment]
@Thalonius Oh, I remember stumbling upon that Tablet Pro Manager app, newer really tried installing the TMP though. Now this helps abandoning the trackpad even further (I'm using Acer R7 and it got the trackpad on the far side, most of the time obscured by screen).

**Comment by TransposonY** [comment]
Ok, I will try to implement continuous gestures, but not in the latest version.

**Comment by TransposonY** [comment]
continuous gesture 927113ed

**Comment by x-iso** [comment]
This is good, but what about other than straight directional gestures? Like continuous rotating gesture or pinch gestur, or diagonal swipes? Hopefully that will be added as well. Thanks for update anyway.

**Comment by jDally987** [comment]
> This is good, but what about other than straight directional gestures? Like continuous rotating gesture or pinch gesture, or diagonal swipes? Hopefully that will be added as well. Thanks for update anyway.

Agree with this, it's kind of weird to have continuous gestures but be restrained to only one direction. The circular motion thing sounds perfect, I'd love to see that implemented if possible. Thanks @TransposonY  for your work, this app is awesome.

**Comment by lveillard** [comment]
+1 to this. A good use case example would be rts games, and using two fingers to move the map in the 8 directions 😅
