### ISSUE TITLE
Seems not working

### ISSUE THREAD

**Issue by Ryouba** [TransposonY/GestureSign#14]
i heard this software when using SAO Utils, whose author says that your software can realise double fingures down to launch his main exe programme. But i don't know if i set wrong or the ACTION doesn't work, i turned all on, double fingures down, two blue lines appears, then no events triggered(i changed the triggering event once, still nothing). What's more, i think the GUI's not very friendly, not so easy to understand. A good project made BY China. Hope to be better. --Ryouba
最开始我是从SAO Utils(刀剑神域3D菜单)的作者那里听说这个软件的，他说这样可以实现双指下滑启动他的exe主程序。但是我不知道是我设置错了还是软件没生效，我把该开的开关都开了，双指下滑，屏幕上有两根蓝色竖杠，然后就啥都没有了（我把触发事件改了也没有什么卵用）。另外，我感觉这个界面还不够友好把，有点看不懂咋用-。-我大中国的好项目！滋磁！——龍羽

**Comment by TransposonY** [comment]
看看指南能帮到您吗
[使用指南](https://zh.gesturesign.win/#/guide)
