### ISSUE TITLE
no stack gesture in last v4.2 version

### ISSUE THREAD

**Issue by motfis** [TransposonY/GestureSign#15]
I just realize that there is no "stack gesture" in the latest version (v4.2)
I hope it will be available again in the next version.

**Comment by TransposonY** [comment]
Just double-click on the gesture pattern and draw another layer of pattern.

**Comment by motfis** [comment]
OK, thanks for the info. There was no explanation about this double click to stack the gestures.
I tried and it was working, _but_ sometimes or many times, it is difficult to make double click, especially using touch screen (I use surface pro 3). I hope in the next version, you will give stack button, like in the previous version.
Thanks!

**Comment by TransposonY** [comment]
The problem has been fixed, it is easy to make double click in version 5.0.
