### ISSUE TITLE
Global action for show/hide touch keyboard doesn't work

### ISSUE THREAD

**Issue by asampal** [TransposonY/GestureSign#16]
I'm using a Surface Pro 4, Windows 10 64 bit CU, GestureSign 5.0

The default, three finger touch gesture to show/hide the touch keyboard doesn't seem to work. I'm pretty sure it was working in an older version of GestureSign.

**Comment by sonst-was** [comment]
It works for me with GestureSign 5.2 (with a two-finger swipe upwards to open and downwards to close the touch keyboard.

**Comment by jrmclau** [comment]
This is not workfing for e on build 17093.rs_prerelease.170202-1400 (Spring Preview, it seems)

**Comment by SultanPepper** [comment]
It works for me when my taskbar is visible, but does not if the taskbar is hidden

**Comment by asampal** [comment]
Never considered it could be the taskbar. Too bad, that's how I keep it.

**Comment by TransposonY** [comment]
Touch keyboard cannot show when the taskbar is hidden af94e7e5
