### ISSUE TITLE
uninst.exe flagged with TrojanDownloader Tovkater.ID in installed v6.0 release

### ISSUE THREAD

**Issue by Mondaynity** [TransposonY/GestureSign#20]
Both Comodo and Panda detect a trojan downloader, but MalwareBytes does not. Assuming it is a false positive, it would be a good idea to submit the executable to the major antivirus providers for verification.

**Comment by TransposonY** [comment]
It is a false positive.
https://forums.comodo.com/av-false-positivenegative-detection-reporting/cis-potential-false-positive-or-actual-trojan-t121441.0.html
