### ISSUE TITLE
有機會替觸控板添加三指拖移功能嗎？

### ISSUE THREAD

**Issue by david50407** [TransposonY/GestureSign#21]
很喜歡這個 project，無論是在觸控屏或是在觸控板上的手勢識別都表現的可圈可點

看起來 Surface 系列的精密觸控板已經可以精準的識別拖移距離以及手指定位了，
是不是有機會添加三指拖移的功能？

**Comment by TransposonY** [comment]
抱歉，GestureSign不會實現此功能

**Comment by david50407** [comment]
thank you

**Comment by lyscop** [comment]
设置触摸板手势调用鼠标手势软件的拖拽快捷键，比如WGesture，不会冲突
