### ISSUE TITLE
Not Working At All On Surface Book 2

### ISSUE THREAD

**Issue by abcjme** [TransposonY/GestureSign#22]
I just did a fresh installation of Windows 10, and this program is almost completely non-functional on my Surface Book 2. Am I doing something wrong???

Here's a 1 minute video example of me trying to use it: 
https://www.dropbox.com/s/vhlml5ha2qnfy2d/gesturesign.mp4?dl=0

**Comment by abcjme** [comment]
I got it working. I had to simultaneously use 1 finger from each hand to get most 2 finger gestures to work. I was under the impression that 2 fingers of the same hand would do.

**Comment by asampal** [comment]
It should work with just one hand, but the timing has to be right - first touch one finger without dragging, then do the drag gesture with another. Of course it's easier to do this with two hands. 

The Surface touch screen sensor has no way of knowing which hand you're using - all touches are the same - you could use toes if you wanted to.

**Comment by david50407** [comment]
It works well on my SB2
