### ISSUE TITLE
Add a way to whitelist programmes instead of blacklisting them

### ISSUE THREAD

**Issue by Somethingweirdhere** [TransposonY/GestureSign#29]
Right now I need to disable GestureSign in all programmes I don't want to use it. I would prefer to just enable it for those I want to use it. Any hope that this can be added in the future?

**Comment by chyangpa** [comment]
@Somethingweirdhere Is your intended white-box function different from turning off 'global actions' and only using actions for specific programs? Gesturesign basically provides 'Actions for web browsers only'.

**Comment by chyangpa** [comment]
@Somethingweirdhere Is your intended white-box function different from turning off 'global actions' and only using actions for specific programs? GestureSign basically provides 'Actions for web browsers only'.

**Comment by Somethingweirdhere** [comment]
Sorry for not figuring this out! You can even enter multiple applications at once. Thanks for the explanation. I am closing this.
