### ISSUE TITLE
Multiple gesture support / "Overlay gesture"

### ISSUE THREAD

**Issue by itamarcu** [TransposonY/GestureSign#39]
Was this feature removed? Right now I find it impossible to add overlayed gestures (such as double-tapping with 3 fingers).

These git issues reference this feature 3 years ago:

https://github.com/TransposonY/GestureSign/issues/10

https://github.com/TransposonY/GestureSign/issues/11

**Comment by itamarcu** [comment]
Nevermind, I figure it out - to use overlayed gestures you need to double-tap an existing gesture.
Then you draw an additional gesture and afterwards you will be able to see both of them in slightly different shades of blue.

I found this in this guide (used google translate):

https://transposony.coding.me/GestureSign/#/guide

**Comment by lyscop** [comment]
7.5 vision, also need to click mouse right before draw the second gesture.
