### ISSUE TITLE
大神，请问多指操作与浏览器的放大冲突怎么处理？

### ISSUE THREAD

**Issue by equatorer** [TransposonY/GestureSign#42]
是这么一个问题！我的设备是surfacego，浏览器是火狐66.2
比如我两指向上表示刷新，但是这个操作可以说是100%会造成浏览器的放缩。

虽然不会影响操作的结果，但是浏览器的网页会时大时小，让人很是烦恼

**Comment by equatorer** [comment]
@TransposonY 

今天已经解决了这个问题了，方法是在火狐浏览器地址栏输入about:config，然后搜索pinch，找到下图的三个“已修改”数据，依次更改即可。

<a href="https://imgchr.com/i/AjPEwt"><img src="https://s2.ax1x.com/2019/04/15/AjPEwt.png" alt="AjPEwt.png" border="0" /></a>

图中的jj可是任意值。

**Comment by lyscop** [comment]
edge的也烦恼

**Comment by equatorer** [comment]
如果用火狐浏览器，是可以关闭放大缩小选项的，好像是config里面



---原始邮件---
发件人: "lyscop"<notifications@github.com&gt;
发送时间: 2020年11月2日(周一) 晚上11:36
收件人: "TransposonY/GestureSign"<GestureSign@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"equatorer"<job_qi@foxmail.com&gt;;
主题: Re: [TransposonY/GestureSign] 大神，请问多指操作与浏览器的放大冲突怎么处理？ (#42)




 
edge的也烦恼
