### ISSUE TITLE
Alt + LEFT and Alt + RIGHT don't work

### ISSUE THREAD

**Issue by SashaIr** [TransposonY/GestureSign#6]
Hello, those two shortcuts don't work in Windows 10 64 bit. I tried several options, but none worked. I'd like to use them in Edge browser, but I can't figure how to do so.

EDIT: It seem not to recognize any shortcut that involves the "Alt" key.

**Comment by TransposonY** [comment]
v2.2 should fix this problem

**Comment by SashaIr** [comment]
It works now! Thank you!
