### ISSUE TITLE
Error message not fully displayed

### ISSUE THREAD

**Issue by sonst-was** [TransposonY/GestureSign#7]
When trying to give a new gesture a name which already exists, the error message cannot be read, because the windows is too small:

![gesturesign](https://cloud.githubusercontent.com/assets/1457478/14261214/e05f4f70-faaf-11e5-9e4a-b39b4d36af3c.PNG)

The error message apparently reads
> The Gesture Name you provided already exists, please provide a different Gesture Name

**Comment by TransposonY** [comment]
Thanks for the feedback.The message will show in another way.
