### ISSUE TITLE
What's difference between the two gestures?

### ISSUE THREAD

**Issue by CoCoThink** [TransposonY/GestureSign#71]
![Snipaste_2020-11-19_13-48-24](https://user-images.githubusercontent.com/10937758/99626811-faa74480-2a6d-11eb-8c78-d64833e4ff11.png)

**Comment by motfis** [comment]
left: 3  finger tap
right: 3 finger tap (x2) --> like double click, you need to tap 2x.

**Comment by CoCoThink** [comment]
Thank you very much!
