### ISSUE TITLE
[Suggestion] Create a gitter.im room for this project

### ISSUE THREAD

**Issue by asampal** [TransposonY/GestureSign#8]
It would be good to have a room on http://gitter.im where people could chat about this project/repo. If you do create one, you can add a badge in the README as link to take people to that room (the option to add a badge is part of the room creation process). 

This tool is really great and deserves to get as much exposure as possible.

**Comment by TransposonY** [comment]
Nice idea,but I prefer a chat room not only for developers.

**Comment by asampal** [comment]
Well, nothing prevents users of all kinds form joining a Gitter chat room. I'm part of several where the talk is not very technical - remember that you can create rooms that are not specific to a GitHub repository. In any case, the point of this issue wasn't to be specific about Gitter, but for there to be a place where people could chat about GestureSign and through which you could gather ideas and get feedback. So, if you have a preferred chat system you want to use, I'd be happy to use that.

One nice thing with gitter is that it integrates very nicely with github issues so that it's easy for anyone to jump to these and be more specific if they want to provide input. As well, they can see when particular issues are being worked on.
