### ISSUE TITLE
Option to hide gesture

### ISSUE THREAD

**Issue by dkrmdi** [TransposonY/GestureSign#88]
Option to hide gestures. I don't want to see my gestures on the screen every time I use my touch pad to move the cursor up and down.

**Comment by Ginterdinger** [comment]
Isnt there an Option for that already? Control Panel -> Options -> Tab: Options -> at the top: "Show Gesture Trail" -> toggle switch on/off
If thats it, close the issue or if not, then define your wish further :D

**Comment by dkrmdi** [comment]
My bad. Problem solved. Thank you.

I'm sorry. I didn't notice the tab at the top.
