### ISSUE TITLE
Matebook E 2022 无法使用 GestureSign

### ISSUE THREAD

**Issue by gl0zzy** [TransposonY/GestureSign#97]
如题, 希望作者能适配

**Comment by seflerZ** [comment]
机器本身与软件没有关系，你使用的是什么版本的系统？有什么错误提示？
There is no difference what hardware you're using since all based on Windows libs. Which OS version are you using and is there any kind of error messages?

**Comment by gl0zzy** [comment]
试过
windows10专业和工作站 21h2
windows11专业 21h2
这几个系统。
软件没有任何错误提示，只是手势没有反应。我向华为官方反应了问题，他们暂时也没有解决方案。

**Comment by seflerZ** [comment]
可以打开一下手势轨迹，看手势是否画出？这种情况一般都是与某个内置的软件冲突了。
Is there any gesture trail genereated if you enable them in the control pannel? Usually it will be incompatbility issue with build in softwares provided by the hardware vendor.

**Comment by gl0zzy** [comment]
打开鼠标手势的话可以画出单指，但是多指不行。
关闭鼠标手势单指和多指都不行。
这是一个普遍存在matebooke的问题。Gestruesign官方QQ群内的matebooke用户都不能正常使用。

**Comment by seflerZ** [comment]
鼠标手势动作可以执行吗？多指触屏可以吗（手势轨迹可以画出吗）？
Will mouse gesture's action execute? How about touch screen gesture (are the gesture trails drawed)?

**Comment by gl0zzy** [comment]
> 鼠标手势动作可以执行吗？多指触屏可以吗（手势轨迹可以画出吗）？
> Will mouse gesture's action execute? How about touch screen gesture (are the gesture trails drawed)? 

鼠标手势可以。触屏不可以，不能画出轨迹

**Comment by seflerZ** [comment]
也就是说除了鼠标可以画出轨迹，触摸板与触屏都不行，对吧？那说明内核功能是正常的，只是触摸屏（板）采集组件受到了阻碍。我个人建议如下：

1. 查看一下 GestureSign.log 日志（如果安装的是便携版，则在 GestureSign/AppData 这个目录里，安装版在 ~/AppData），是否有详细原因
2. 使用 msconfig 进行一次诊断启动，即加载最小资源，看看是否正常

如果仍然不能正常且没有日志，只能下载源码编译并调试了，我这里并没有 MateBook E 所以帮不上忙。我自己在 win10，win11 上都安装了 GestureSign 并正常工作，因此为软件本身的原因应该很小。

In that case touchpad and touch screen gesture all failed except the mouse gesture. Which concludes the gureture core works but the point capture components for touch screen and pad. My own suggestions are:

1. Check 'GestureSign.log' for better details (which locates in 'GestureSign/AppData' if you have portable version and '~/AppData' if you got installed version)
2. Start 'msconfig' and doing a diagnose startup which loads basic drivers and services and then have a test

If both options fail, you can only download the source code and debug them. I don't have such device, so be sorry. I've installed GestureSign both on win10 and win11 and it works great. I still prefer environment issue than application bugs in GestureSign.

**Comment by luluatnet** [comment]
> 也就是说除了鼠标可以画出轨迹，触摸板与触屏都不行，对吧？那说明内核功能是正常的，只是触摸屏（板）采集组件受到了阻碍。我个人建议如下：
> 
> 1. 查看一下 GestureSign.log 日志（如果安装的是便携版，则在 GestureSign/AppData 这个目录里，安装版在 ~/AppData），是否有详细原因
> 2. 使用 msconfig 进行一次诊断启动，即加载最小资源，看看是否正常
> 
> 如果仍然不能正常且没有日志，只能下载源码编译并调试了，我这里并没有 MateBook E 所以帮不上忙。我自己在 win10，win11 上都安装了 GestureSign 并正常工作，因此为软件本身的原因应该很小。
> 
> In that case touchpad and touch screen gesture all failed except the mouse gesture. Which concludes the gureture core works but the point capture components for touch screen and pad. My own suggestions are:
> 
> 1. Check 'GestureSign.log' for better details (which locates in 'GestureSign/AppData' if you have portable version and '~/AppData' if you got installed version)
> 2. Start 'msconfig' and doing a diagnose startup which loads basic drivers and services and then have a test
> 
> If both options fail, you can only download the source code and debug them. I don't have such device, so be sorry. I've installed GestureSign both on win10 and win11 and it works great. I still prefer environment issue than application bugs in GestureSign.

1.普通运行GestureSign，log文件中无任何报错
2、使用诊断启动，再次运行，log报错如下：
[2022-05-20 22:53:09] [GestureSign.Common v8.1.0.0] Application.Current.DispatcherUnhandledException

[2022-05-20 22:53:09] [GestureSign.Common v8.1.0.0] System.InvalidOperationException: 无法打开计算机 . 上的日志 Application。Windows 未提供错误代码。 ---> System.ComponentModel.Win32Exception: RPC 服务器不可用。
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Diagnostics.EventLogInternal.OpenForRead(String currentMachineName)
   在 System.Diagnostics.EventLogInternal.get_EntryCount()
   在 GestureSign.ControlPanel.MainWindow.ExistsNewerErrorLog()
   在 GestureSign.ControlPanel.MainWindow.MetroWindow_Loaded(Object sender, RoutedEventArgs e)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   在 System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   在 MS.Internal.LoadedOrUnloadedOperation.DoWork()
   在 System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   在 System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   在 System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   在 System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   在 System.Windows.Interop.HwndTarget.OnResize()
   在 System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   在 System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2022-05-20 22:53:09] [GestureSign.Common v8.1.0.0] System.ComponentModel.Win32Exception (0x80004005): RPC 服务器不可用。

**Comment by zl70971** [comment]
请问目前有解决方案了吗 谢谢 同为mbe2022

**Comment by gl0zzy** [comment]
> 请问目前有解决方案了吗 谢谢 同为mbe2022

没有解决方案

**Comment by oldkingOK** [comment]
设备：Matebook e go
系统版本：Windows Pro 23H2
测试流程：
1. 打开应用
2. 此时触摸板手势可正常使用
3. 手指点击屏幕尝试触屏手势是否可以正常使用——无法使用
4. 此时触摸板手势也无法使用——重启应用又可以使用

Device: Matebook e go
System version: Windows Pro 23H2 arm64
Testing process:
1. Open the application
2. At this time the touchpad gestures can be used normally
3. Tap the screen with finger to try to see if the touch screen gestures can be used normally - it can't be used.
4. At this time the touchpad gestures can not be used - restart the application can be used again

**Comment by gl0zzy** [comment]
> 设备：Matebook e go 系统版本：Windows Pro 23H2 测试流程：
> 
> 1. 打开应用
> 2. 此时触摸板手势可正常使用
> 3. 手指点击屏幕尝试触屏手势是否可以正常使用——无法使用
> 4. 此时触摸板手势也无法使用——重启应用又可以使用
> 
> Device: Matebook e go System version: Windows Pro 23H2 arm64 Testing process:
> 
> 1. Open the application
> 2. At this time the touchpad gestures can be used normally
> 3. Tap the screen with finger to try to see if the touch screen gestures can be used normally - it can't be used.
> 4. At this time the touchpad gestures can not be used - restart the application can be used again

解决不了的，除此之外华为的设备还有不少的问题。我已经换成了 surface。

**Comment by oldkingOK** [comment]
> 解决不了的，除此之外华为的设备还有不少的问题。我已经换成了 surface。

感谢你的快速回复！我会进行一些尝试，然后再决定是否放弃，如果能提供一些思路，我会非常感谢

**Comment by Darkee919** [comment]
> 设备：Matebook e go 系统版本：Windows Pro 23H2 测试流程：
> 
> 1. 打开应用
> 2. 此时触摸板手势可正常使用
> 3. 手指点击屏幕尝试触屏手势是否可以正常使用——无法使用
> 4. 此时触摸板手势也无法使用——重启应用又可以使用
> 
> Device: Matebook e go System version: Windows Pro 23H2 arm64 Testing process:
> 
> 1. Open the application
> 2. At this time the touchpad gestures can be used normally
> 3. Tap the screen with finger to try to see if the touch screen gestures can be used normally - it can't be used.
> 4. At this time the touchpad gestures can not be used - restart the application can be used again

我的设备是matebook e 2023，也存在同样的问题，特别是在使用远程PC时相当苦恼。希望能有办法解决这个问题，感谢作者大大。
